# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Phone-Island Release and Publish on tags

on:
  push:
    tags:
      - '**'

jobs:
  cdn-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: Install dependencies
        run: npm ci
      - name: Run widget build
        run: npm run build:widget
      - name: 'Commit and publish to cdn'
        uses: EndBug/add-and-commit@v4
        with:
          author_name: NethBot
          author_email: NethBot@users.noreply.github.com
          message: 'widget: release for jsDelivr'
          add: 'dist-widget/ --force'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-publish:
    needs: cdn-publish
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: 'Prepare node setup'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Publish module
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Install NS8 Release Module Extension
        run: gh extension install NethServer/gh-ns8-release-module
      - name: Create Release
        run: gh ns8-release-module create --repo ${{ github.repository }} --release-name ${{ github.ref }}
